FROM node:latest

LABEL name="app-name"
ENV APP_PORT=3000 APP_DIR=/app

WORKDIR ${APP_DIR}

ADD package.json .
ADD package-lock.json .
ADD . .

RUN npm install 

HEALTHCHECK --interval=15s --timeout=10s --retries=3 CMD curl -f http://localhost:${APP_PORT}/health || exit 1

EXPOSE ${APP_PORT}

ENTRYPOINT [ "node", "main.js" ]

CMD [ "" ]