FROM python:3-alpine

LABEL name="flaskapp"
LABEL maintainer="developer-name"

ENV APP_DIR=/app APP_PORT=5000

WORKDIR ${APP_DIR}

ADD requirements.txt .
RUN pip install -r requirements.txt

ADD app.py .

HEALTHCHECK --interval=15s --timeout=10s --retries=3 CMD curl -f http://localhost:${APP_PORT}/ || exit 1

EXPOSE ${APP_PORT}

#ENTRYPOINT [ "python", "app.py" ]
CMD gunicorn -b 0.0.0.0:${APP_PORT} app